# This file provides instructions for packaging.

`Test-Tabs`
	perl_version_from m`Test::Tabs`;
	version_from      m`Test::Tabs`;
	readme_from       m`Test::Tabs`;
	test_requires     p`Test::More 0.61`.

