@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Test-Tabs/project>
	deps:runtime-requirement         [ deps:on "perl 5.008"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

